import {Component, Inject, OnInit, Optional} from '@angular/core';
import {ConstantService} from '../../../core/services/constant.service';
import {ConfigOptionsService} from '../../../core/services/config-options.service';
import {Generated} from '../../../core/services/generator';
import {LocalStorageService} from '../../../core/services/local-storage.service';

@Component({
  selector: 'app-about',
  templateUrl: './about.component.html',
  styleUrls: ['./about.component.less']
})
export class AboutComponent {

  constructor(
    @Optional() private constants: ConstantService,
    @Optional() private config: ConfigOptionsService,
    @Optional() @Inject(LocalStorageService) private localStorage: LocalStorageService,
    @Optional() @Inject(Generated) private randomValue: string
  ) {
    console.log('Constants: ', this.constants);

    console.log('Config options: getAll', this.config.getAll());
    console.log('Config options: id', this.config.get('id'));
    console.log('Config options: user', this.config.get('user'));

    console.log('Generated by factory: ', this.randomValue);

    this.localStorage.setItem('email', this.config.get('email'));
    console.log('Email from localStorage: ', this.localStorage.getItem('email'));
  }
}
